Разметка главной страницы!
htmlacademy-htmlcss/1799851-sedona-31 pull request #3
Opened 2021-05-26 15:59 UTC by chernii5k

2021-05-26 18:12 UTC, Ankhena requested changes

2021-05-26 18:12 UTC, Ankhena commented on index.html
>  <html lang="ru">
После изменений в коде, обязательно нужно проверять его [валидатором](https://validator.w3.org/nu/).

2021-05-26 18:12 UTC, Ankhena commented on index.html
> +        <h2>Welocme</h2>
Опечатка Welcome.
Было бы хорошо, если бы заголовок помогал понять о чем секция и желательно на языке страницы.

2021-05-26 18:12 UTC, Ankhena commented on index.html
> +        <img src="img/wellcome-to-sedona.png" width="456,65" height="350,88" alt="Добро пожаловать в Седону!">
Снова опечатка welcome :)
Про картинки потом поговорим, в задании про графику.

2021-05-26 18:12 UTC, Ankhena commented on index.html
> +        <ul>
Логически это не один список из 8 пунктов. 
Ведь причин в макете 5 штук. Значит и список должен быть из 5 элементов.

2021-05-26 18:12 UTC, Ankhena commented on index.html
> +            <h2>Жилье</h2>
Жилье-Еда-Сувениры  - это список вложенный в первую причину.

2021-05-26 18:12 UTC, Ankhena commented on index.html
> +            <img src="img/red-mountaines.jpg" width="800" height="256" alt="Красные горы Аризоны">
Суперский alt - мне нравится.

2021-05-27 07:23 UTC, chernii5k commented
Исправление ошибок

2021-05-27 09:40 UTC, merged